import { IPaginatedResult } from "@shared/types/paginated-result";
import { IPaginationQuery, ISortQuery } from "@shared/types/pagination.types";

/**
 * Mentor Appeal Record Interface (导师申诉记录接口)
 *
 * This interface represents a mentor appeal record in the system
 * (该接口表示系统中的导师申诉记录)
 */
export interface IMentorAppeal {
  // ========== Primary Key ==========
  /**
   * Appeal ID (申诉ID)
   * Primary key generated by database
   * (数据库生成的主键)
   */
  id: string;

  // ========== Participants ==========
  /**
   * Mentor ID (导师ID)
   * References: mentor.id
   * (引用导师表的ID)
   */
  mentorId: string;

  /**
   * Counselor ID (处理顾问ID)
   * References: counselor.id
   * (引用顾问表的ID)
   */
  counselorId: string;

  /**
   * Student ID (学生ID)
   * References: user.id
   * (引用用户表的ID)
   */
  studentId: string;

  // ========== Related Financial Records ==========
  /**
   * Mentor Payable Ledger ID (关联应付账款ID)
   * References: mentor_payable_ledgers.id
   * Optional: Appeals may not be tied to a specific transaction
   * (关联应付账款记录的ID - 可选)
   */
  mentorPayableId?: string;

  /**
   * Settlement Ledger ID (关联结算ID)
   * References: settlement_ledgers.id
   * Optional: Appeals may not be tied to a specific settlement batch
   * (关联结算记录的ID - 可选)
   */
  settlementId?: string;

  // ========== Appeal Details ==========
  /**
   * Appeal Type (申诉类型)
   * Values: billing_error, missing_service, price_dispute, other
   * (申诉类型：费用计算错误、遗漏服务记录、价格争议、其他)
   */
  appealType: string;

  /**
   * Appeal Amount (申诉金额)
   * The amount the mentor is disputing or requesting
   * Precision: 12 digits total, 2 decimal places
   * Note: Stored as numeric(12,2) in database, returned as string by Drizzle ORM
   * (申诉金额 - 导师争议或申请的金额，数据库返回为字符串)
   */
  appealAmount: string;

  /**
   * Currency (货币类型)
   * ISO 4217 currency code
   * (货币 - ISO 4217货币代码)
   */
  currency: string;

  /**
   * Payment Month (付款月份)
   * Format: YYYY-MM
   * The month this appeal amount should be recorded in
   * (付款月份 - 该申诉金额本应记入的月份，格式为YYYY-MM)
   */
  paymentMonth: string;

  /**
   * Appeal Reason (申诉理由)
   * Detailed description of why the mentor is appealing
   * (申诉的详细理由和描述)
   */
  reason: string;

  /**
   * Status (申诉状态)
   * Values: PENDING, APPROVED, REJECTED
   * (申诉状态：待处理、已批准、已驳回)
   */
  status: string;

  /**
   * Rejection Reason (驳回理由)
   * Required only when status = REJECTED
   * (驳回申诉的理由)
   */
  rejectionReason?: string;

  /**
   * Comments (申诉评论)
   * Additional comments added during appeal processing
   * (申诉处理过程中添加的额外评论)
   */
  comments?: string;

  // ========== Processing Records ==========
  /**
   * Approved By (审批人ID)
   * References: counselor.id or other user tables
   * Set when status changes to APPROVED
   * (审批该申诉的用户ID)
   */
  approvedBy?: string;

  /**
   * Approved At (审批时间)
   * Timestamp when status changed to APPROVED
   * (申诉被批准的时间戳)
   */
  approvedAt?: Date;

  /**
   * Rejected By (驳回人ID)
   * References: counselor.id or other user tables
   * Set when status changes to REJECTED
   * (驳回该申诉的用户ID)
   */
  rejectedBy?: string;

  /**
   * Rejected At (驳回时间)
   * Timestamp when status changed to REJECTED
   * (申诉被驳回的时间戳)
   */
  rejectedAt?: Date;

  // ========== Audit Trail ==========
  /**
   * Created By (创建人ID)
   * References: identity.users.id
   * The mentor who submitted the appeal
   * (提交申诉的导师ID)
   */
  createdBy: string;

  /**
   * Created At (创建时间)
   * Timestamp when the appeal was submitted
   * (申诉提交的时间戳)
   */
  createdAt: Date;
}

/**
 * Create Appeal DTO (创建申诉的数据传输对象)
 *
 * This interface defines the data required to create a new appeal
 * (该接口定义创建新申诉所需的数据)
 */
export interface ICreateAppealDTO {
  /**
   * Mentor ID (导师ID)
   * The mentor submitting the appeal
   * (提交申诉的导师ID)
   */
  mentorId: string;

  /**
   * Counselor ID (处理顾问ID)
   * The counselor assigned to process the appeal
   * (指定处理该申诉的顾问ID)
   */
  counselorId: string;

  /**
   * Student ID (学生ID)
   * The student related to this appeal
   * (关联的学生ID)
   */
  studentId: string;

  /**
   * Mentor Payable Ledger ID (关联应付账款ID)
   * Optional: Link to the specific transaction being disputed
   * (关联被争议的应付账款记录ID - 可选)
   */
  mentorPayableId?: string;

  /**
   * Settlement ID (关联结算ID)
   * Optional: Link to the settlement batch (if applicable)
   * (关联结算批次ID - 可选)
   */
  settlementId?: string;

  /**
   * Appeal Type (申诉类型)
   * Values: billing_error, missing_service, price_dispute, other
   * (申诉类型)
   */
  appealType: string;

  /**
   * Appeal Amount (申诉金额)
   * The amount being disputed or requested
   * Precision: 12 digits total, 2 decimal places
   * Note: Use string to match database numeric(12,2) type
   * (申诉金额 - 使用字符串匹配数据库numeric类型)
   */
  appealAmount: string;

  /**
   * Currency (货币类型)
   * ISO 4217 currency code
   * (货币类型)
   */
  currency: string;

  /**
   * Payment Month (付款月份)
   * Format: YYYY-MM
   * The month this appeal amount should be recorded in
   * (付款月份 - 该申诉金额本应记入的月份，格式为YYYY-MM)
   */
  paymentMonth: string;

  /**
   * Reason (申诉理由)
   * Detailed description of the appeal
   * (申诉的详细理由)
   */
  reason: string;
}

/**
 * Appeal Search DTO (申诉搜索条件的数据传输对象)
 *
 * This interface defines the filter criteria for searching appeals
 * (该接口定义搜索申诉的筛选条件)
 */
export interface IAppealSearchDTO {
  /**
   * Mentor ID Filter (导师ID筛选)
   * Filter appeals by specific mentor
   * (按导师筛选申诉)
   */
  mentorId?: string;

  /**
   * Counselor ID Filter (顾问ID筛选)
   * Filter appeals assigned to specific counselor
   * (按处理顾问筛选申诉)
   */
  counselorId?: string;

  /**
   * Status Filter (状态筛选)
   * Filter appeals by status: PENDING, APPROVED, REJECTED
   * (按状态筛选申诉)
   */
  status?: string;

  /**
   * Start Date Filter (开始日期筛选)
   * Filter appeals created on or after this date
   * (筛选在此日期及之后创建的申诉)
   */
  startDate?: Date;

  /**
   * End Date Filter (结束日期筛选)
   * Filter appeals created on or before this date
   * (筛选在此日期及之前创建的申诉)
   */
  endDate?: Date;

  /**
   * Appeal Type Filter (申诉类型筛选)
   * Filter appeals by type
   * (按申诉类型筛选)
   */
  appealType?: string;

  /**
   * Minimum Amount Filter (最小金额筛选)
   * Filter appeals with appealAmount >= this value
   * Stored as string to match database numeric type
   * (筛选申诉金额大于等于此值的申诉，使用字符串匹配数据库numeric类型)
   */
  minAmount?: string;

  /**
   * Maximum Amount Filter (最大金额筛选)
   * Filter appeals with appealAmount <= this value
   * Stored as string to match database numeric type
   * (筛选申诉金额小于等于此值的申诉，使用字符串匹配数据库numeric类型)
   */
  maxAmount?: string;
}

/**
 * Mentor Appeal Service Interface (导师申诉服务接口)
 *
 * Defines the contract for mentor appeal business logic operations
 * (定义导师申诉业务逻辑操作的契约)
 */
export interface IMentorAppealService {
  /**
   * Create Appeal (创建申诉)
   *
   * Creates a new mentor appeal with PENDING status
   * Validates input data and publishes MENTOR_APPEAL_CREATED_EVENT
   *
   * @param dto - Create appeal data (创建申诉的数据)
   * @param createdByUserId - ID of the mentor submitting the appeal (提交申诉的导师ID)
   * @returns Created appeal record (创建的申诉记录)
   */
  createAppeal(
    dto: ICreateAppealDTO,
    createdByUserId: string,
  ): Promise<IMentorAppeal>;

  /**
   * Find One Appeal (查询单个申诉)
   *
   * Retrieves a single appeal by ID or other conditions
   *
   * @param conditions - ID or filter conditions (ID或筛选条件)
   * @returns Appeal record or null (申诉记录或null)
   */
  findOne(
    conditions: Partial<IMentorAppeal> | { id: string },
  ): Promise<IMentorAppeal | null>;

  /**
   * Search Appeals (搜索申诉列表)
   *
   * Retrieves a paginated list of appeals matching the filter criteria
   * Supports pagination and sorting
   *
   * @param filter - Search filter criteria (搜索筛选条件)
   * @param pagination - Pagination parameters (分页参数)
   * @param sort - Sort parameters (排序参数)
   * @returns Paginated result with appeal records (包含申诉记录的分页结果)
   */
  search(
    filter: IAppealSearchDTO,
    pagination: IPaginationQuery,
    sort?: ISortQuery,
  ): Promise<IPaginatedResult<IMentorAppeal>>;

  /**
   * Approve Appeal (批准申诉)
   *
   * Approves a pending appeal and updates its status to APPROVED
   * Validates that the appeal exists and is in PENDING status
   * Verifies that the approver matches the assigned counselor
   * Records approval information and publishes MENTOR_APPEAL_APPROVED_EVENT
   * If linked to a payable ledger, creates an adjustment record
   * If original appeal amount is invalid, uses provided appealAmount and currency
   *
   * @param id - ID of the appeal to approve (要批准的申诉ID)
   * @param approvedByUserId - ID of the counselor approving (批准该申诉的顾问ID)
   * @param appealAmount - New appeal amount if original is invalid (如果原始金额无效，提供新的申诉金额)
   * @param currency - New currency if original is invalid (如果原始金额无效，提供新的货币类型)
   * @param comments - Additional comments about the approval (关于批准的额外评论)
   * @returns Updated appeal record (更新后的申诉记录)
   * @throws Error if appeal not found, status not PENDING, or permission denied
   */
  approveAppeal(
    id: string,
    approvedByUserId: string,
    appealAmount?: number,
    currency?: string,
    comments?: string
  ): Promise<IMentorAppeal>;

  /**
   * Reject Appeal (驳回申诉)
   *
   * Rejects a pending appeal and updates its status to REJECTED
   * Validates that the appeal exists and is in PENDING status
   * Verifies that the rejector matches the assigned counselor
   * Records rejection reason, who rejected, and when
   * Publishes MENTOR_APPEAL_REJECTED_EVENT
   *
   * @param id - ID of the appeal to reject (要驳回的申诉ID)
   * @param dto - Rejection data including reason (包含驳回理由的数据)
   * @param rejectedByUserId - ID of the counselor rejecting (驳回该申诉的顾问ID)
   * @returns Updated appeal record (更新后的申诉记录)
   * @throws Error if appeal not found, status not PENDING, or permission denied
   */
  rejectAppeal(
    id: string,
    dto: { rejectionReason: string },
    rejectedByUserId: string,
  ): Promise<IMentorAppeal>;
}
